In [33]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [34]:
data = pd.read_csv("./database_F.csv", sep=',', index_col=0)
data

N1                       N2  \
0       71.679,27.885,13.362      75.126,29.191,8.911   
1       11.903,62.561,20.255      12.89,67.843,20.548   
2       52.497,35.902,45.669      57.25,38.924,45.457   
3        -1.686,76.373,54.02     -1.723,78.977,59.081   
4         8.277,2.841,35.275      12.066,1.936,39.164   
..                       ...                      ...   
244   90.763,-22.623,-11.049   92.213,-24.133,-16.157   
245  104.388,-28.521,-84.394  102.175,-29.458,-89.851   
246      7.841,-42.465,50.44      9.21,-37.347,49.237   
247  87.375,-117.074,-32.511  90.545,-113.433,-35.177   
248   52.339,-23.045,-58.864   56.951,-26.375,-57.946   

                          N3                       N4  \
0        80.361,30.047,8.043     82.139,32.527,13.272   
1       11.485,73.132,20.547      7.281,72.722,16.628   
2       62.475,39.792,45.684     63.627,35.696,49.801   
3       -0.723,84.602,63.317     -1.274,87.084,57.332   
4        15.723,4.163,42.831      18.227,9.024,40.773   
..                       ...                      ...   
244   90.551,-23.767,-21.328    84.69,-23.522,-20.343   
245  101.665,-27.911,-94.949  102.179,-21.984,-93.994   
246     9.272,-33.763,45.172     9.899,-37.668,40.687   
247   93.248,-108.89,-34.711  89.758,-106.055,-30.585   
248   60.587,-30.619,-57.807   56.924,-34.917,-59.311   

                          N5                      N6  class  
0       83.259,38.334,15.381    81.294,43.869,14.935      1  
1         5.763,72.86,10.991      7.417,72.774,5.347      1  
2       64.509,34.358,55.361    63.005,35.335,60.758      1  
3        5.354,88.888,55.743    12.345,90.194,56.876      1  
4       22.603,10.952,36.499     25.817,10.06,32.144      1  
..                       ...                     ...    ...  
244   79.986,-27.323,-20.876  77.667,-32.861,-20.317      1  
245    98.762,-17.15,-93.642  93.545,-14.985,-91.353      1  
246    14.471,-39.674,37.477   19.708,-41.493,36.389      1  
247  85.596,-101.754,-30.875    81.4,-99.066,-33.184      1  
248   52.824,-38.738,-58.433  49.976,-41.127,-54.043      1  

[249 rows x 7 columns]

In [35]:
#since it is written as strings we need to change the format 
for column in data.columns[:-1]:
    data[column] = data[column].apply(lambda x: np.array(list(map(float, x.split(',')))))
data['class'] = 1
data

N1                           N2  \
0       [71.679, 27.885, 13.362]      [75.126, 29.191, 8.911]   
1       [11.903, 62.561, 20.255]      [12.89, 67.843, 20.548]   
2       [52.497, 35.902, 45.669]      [57.25, 38.924, 45.457]   
3        [-1.686, 76.373, 54.02]     [-1.723, 78.977, 59.081]   
4         [8.277, 2.841, 35.275]      [12.066, 1.936, 39.164]   
..                           ...                          ...   
244   [90.763, -22.623, -11.049]   [92.213, -24.133, -16.157]   
245  [104.388, -28.521, -84.394]  [102.175, -29.458, -89.851]   
246      [7.841, -42.465, 50.44]      [9.21, -37.347, 49.237]   
247  [87.375, -117.074, -32.511]  [90.545, -113.433, -35.177]   
248   [52.339, -23.045, -58.864]   [56.951, -26.375, -57.946]   

                              N3                           N4  \
0        [80.361, 30.047, 8.043]     [82.139, 32.527, 13.272]   
1       [11.485, 73.132, 20.547]      [7.281, 72.722, 16.628]   
2       [62.475, 39.792, 45.684]     [63.627, 35.696, 49.801]   
3       [-0.723, 84.602, 63.317]     [-1.274, 87.084, 57.332]   
4        [15.723, 4.163, 42.831]      [18.227, 9.024, 40.773]   
..                           ...                          ...   
244   [90.551, -23.767, -21.328]    [84.69, -23.522, -20.343]   
245  [101.665, -27.911, -94.949]  [102.179, -21.984, -93.994]   
246     [9.272, -33.763, 45.172]     [9.899, -37.668, 40.687]   
247   [93.248, -108.89, -34.711]  [89.758, -106.055, -30.585]   
248   [60.587, -30.619, -57.807]   [56.924, -34.917, -59.311]   

                              N5                          N6  class  
0       [83.259, 38.334, 15.381]    [81.294, 43.869, 14.935]      1  
1         [5.763, 72.86, 10.991]      [7.417, 72.774, 5.347]      1  
2       [64.509, 34.358, 55.361]    [63.005, 35.335, 60.758]      1  
3        [5.354, 88.888, 55.743]    [12.345, 90.194, 56.876]      1  
4       [22.603, 10.952, 36.499]     [25.817, 10.06, 32.144]      1  
..                           ...                         ...    ...  
244   [79.986, -27.323, -20.876]  [77.667, -32.861, -20.317]      1  
245    [98.762, -17.15, -93.642]  [93.545, -14.985, -91.353]      1  
246    [14.471, -39.674, 37.477]   [19.708, -41.493, 36.389]      1  
247  [85.596, -101.754, -30.875]    [81.4, -99.066, -33.184]      1  
248   [52.824, -38.738, -58.433]  [49.976, -41.127, -54.043]      1  

[249 rows x 7 columns]

In [36]:
#stems
d1 = pd.read_csv("./stems_database_P'.csv", sep=',', index_col=0)
for column in d1.columns[:-1]:
    d1[column] = d1[column].apply(lambda x: np.array(list(map(float, x.split(',')))))
d1 = d1.reset_index(drop=True)
d1

#hairpins
d2 = pd.read_csv("./hairpins_database_P.csv", sep=',', index_col=0)
for column in d2.columns[:-1]:
    d2[column] = d2[column].apply(lambda x: np.array(list(map(float, x.split(',')))))
d2 = d2.reset_index(drop=True)
d2

#internal loops
d3 = pd.read_csv("./loops_database_P.csv", sep=',', index_col=0)
for column in d3.columns[:-1]:
    d3[column] = d3[column].apply(lambda x: np.array(list(map(float, x.split(',')))))
d3 = d3.reset_index(drop=True)
d3

#ends
d4 = pd.read_csv("./ends_database_P.csv", sep=',', index_col=0)
for column in d4.columns[:-1]:
    d4[column] = d4[column].apply(lambda x: np.array(list(map(float, x.split(',')))))
d4 = d4.reset_index(drop=True)
d4

#mix
d5 = pd.read_csv("./mix_database_P'.csv", sep=',', index_col=0)
for column in d5.columns[:-1]:
    d5[column] = d5[column].apply(lambda x: np.array(list(map(float, x.split(',')))))
d5 = d5.reset_index(drop=True)
d5

#mix_with_seqs_assigned
d5v2 = pd.read_csv("./mix_database_P'.csv", sep=',', index_col=0)
for column in d5v2.columns[:-1]:
    d5v2[column] = d5v2[column].apply(lambda x: np.array(list(map(float, x.split(',')))))
d5v2 = d5v2.reset_index(drop=True)
d5v2

data_full = pd.concat([data, d1, d2, d3, d4, d5v2[:70]])
data_full

N1                              N2  \
0         [71.679, 27.885, 13.362]         [75.126, 29.191, 8.911]   
1         [11.903, 62.561, 20.255]         [12.89, 67.843, 20.548]   
2         [52.497, 35.902, 45.669]         [57.25, 38.924, 45.457]   
3          [-1.686, 76.373, 54.02]        [-1.723, 78.977, 59.081]   
4           [8.277, 2.841, 35.275]         [12.066, 1.936, 39.164]   
..                             ...                             ...   
65     [132.011, 190.437, 175.547]     [125.949, 189.833, 178.571]   
66        [23.333, 56.107, 24.494]        [20.137, 54.122, 18.265]   
67      [223.11, 170.001, 246.614]     [220.803, 164.701, 242.708]   
68       [-56.781, 59.391, 72.597]       [-52.814, 60.944, 69.741]   
69  [69.73546, 47.97945, 22.29318]  [71.96684, 52.44792, 26.08686]   

                                N3                             N4  \
0          [80.361, 30.047, 8.043]       [82.139, 32.527, 13.272]   
1         [11.485, 73.132, 20.547]        [7.281, 72.722, 16.628]   
2         [62.475, 39.792, 45.684]       [63.627, 35.696, 49.801]   
3         [-0.723, 84.602, 63.317]       [-1.274, 87.084, 57.332]   
4          [15.723, 4.163, 42.831]        [18.227, 9.024, 40.773]   
..                             ...                            ...   
65     [124.837, 184.873, 181.566]    [126.079, 182.583, 178.104]   
66         [19.26, 52.457, 13.766]        [22.285, 49.498, 8.239]   
67     [221.244, 160.263, 239.369]     [225.616, 156.34, 236.291]   
68       [-55.822, 63.467, 65.126]      [-58.677, 65.879, 60.888]   
69  [72.34578, 56.70649, 30.16463]  [71.1807, 58.10714, 35.30685]   

                                N5                              N6  class  
0         [83.259, 38.334, 15.381]        [81.294, 43.869, 14.935]      1  
1           [5.763, 72.86, 10.991]          [7.417, 72.774, 5.347]      1  
2         [64.509, 34.358, 55.361]        [63.005, 35.335, 60.758]      1  
3          [5.354, 88.888, 55.743]        [12.345, 90.194, 56.876]      1  
4         [22.603, 10.952, 36.499]         [25.817, 10.06, 32.144]      1  
..                             ...                             ...    ...  
65     [126.347, 182.483, 172.324]       [125.139, 180.4, 166.288]      0  
66           [26.254, 48.644, 4.7]         [32.002, 46.334, 4.269]      0  
67       [222.44, 153.18, 232.529]     [223.586, 147.392, 231.026]      0  
68       [-62.656, 67.258, 56.782]        [-68.329, 63.59, 55.349]      0  
69  [70.34999, 55.80605, 40.19811]  [69.05458, 51.01681, 37.84402]      0  

[485 rows x 7 columns]

In [37]:
def count_planar_angle(p1, p2, p3):
    b1 = p2 - p1
    b2 = p2 - p3

    angle = np.arccos(np.dot(b1, b2) / (np.linalg.norm(b1) * np.linalg.norm(b2)))
    return np.degrees(angle)

def count_torsion_angle(p1, p2, p3, p4):
    b1 = p2 - p1
    b2 = p3 - p2
    b3 = p4 - p3

    n1 = np.cross(b1, b2)
    n2 = np.cross(b2, b3)

    torsion = np.arctan2(
        np.dot(np.cross(n1, n2), b2 * np.linalg.norm(b2)), np.dot(n1, n2)
    )
    return np.degrees(torsion)

def count_euclid_dist(a,b):
    return np.sqrt((a[0] - b[0])**2 + (a[1] - b[1])**2 + (a[2] - b[2])**2)

In [38]:
planar_angles_full = []
cols =[]
for row in data_full.iloc[:,:-1].iterrows():
    tmp = []
    for i in range(len(row[1]) - 2):
        for j in range(i + 1, len(row[1]) - 1):
            for k in range(j + 1, len(row[1])):
                tmp.append(count_planar_angle(row[1][i], row[1][j], row[1][k]))
                if len(cols) < 20:
                    cols.append((i,j,k))
    planar_angles_full.append(tmp)

planar_angles_full = pd.DataFrame(planar_angles_full)
planar_angles_full.columns=cols
print(planar_angles_full)

      (0, 1, 2)   (0, 1, 3)   (0, 1, 4)   (0, 1, 5)   (0, 2, 3)   (0, 2, 4)  \
0    137.839805  100.205275   98.031855   97.956593   83.608979   91.946891   
1    154.359694  114.961624  103.852525  100.259138   86.501496   88.408977   
2    156.532646  114.612641  104.592758   98.082748   86.041682   89.669105   
3    152.937440  105.008780   96.914646   99.781813   63.802542   77.195882   
4    147.261946  116.237231  105.980836  100.468988   98.768014   95.742054   
..          ...         ...         ...         ...         ...         ...   
480  117.927979   92.526799   75.117653   75.428839   68.878788   59.669807   
481  164.111401  142.303180  131.077569  116.499055  133.570495  124.681217   
482  156.142769  136.131746  154.124673  152.996751  129.997702  162.705528   
483   99.568944   99.285071   94.981267   81.411478  143.209288  136.682369   
484  162.516019  149.324156  135.179147  114.488806  139.122213  122.215503   

      (0, 2, 5)   (0, 3, 4)   (0, 3, 5)   (0, 4, 5)

In [39]:
from itertools import combinations
torsion_angles = []
cols=[]
for row in data_full.iloc[:,:-1].iterrows():
    tmp = []
    for i in range(len(row[1])-3):  
        for j in range(i+1, len(row[1])-2):  
            for k in range(j+1, len(row[1])-1):
                for l in range(k+1, len(row[1])):
                    tmp.append(count_torsion_angle(row[1][i], row[1][j], row[1][k], row[1][l]))
                    if len(cols) < 15:
                        cols.append((i,j,k,l))
    # for combo in combinations(row[1], 4):
    #     tmp.append(count_torsion_angle(combo[0], combo[1], combo[2], combo[3]))
    torsion_angles.append(tmp)

torsion_angles_full = pd.DataFrame(torsion_angles)
torsion_angles_full.columns=cols

### SKALOWANIE ZEBY NIE BYLO UJEMNYCH ###
for i in range(torsion_angles_full.shape[0]):
    torsion_angles_full.iloc[i] = torsion_angles_full.iloc[i].apply(lambda x: x+360 if x < 0 else x)
    
print(torsion_angles_full)

     (0, 1, 2, 3)  (0, 1, 2, 4)  (0, 1, 2, 5)  (0, 1, 3, 4)  (0, 1, 3, 5)  \
0      273.133430    271.382076    270.627788    270.056945    270.000052   
1      272.633111    271.474222    270.775931    270.462652    270.256167   
2      273.145590    271.819693    271.070733    270.477542    270.342320   
3       86.874752    273.363480    271.373966    270.168052    270.004662   
4      272.536161    271.230159    270.730204    270.270663    270.199888   
..            ...           ...           ...           ...           ...   
480    271.335485    270.886351    270.615783    270.609288    270.435480   
481     52.648349    292.389649     20.347582    271.075175    280.579106   
482    355.745075    270.688256     88.152292    268.259792     92.370225   
483     88.914979    273.204348    272.229355    270.679652    270.569412   
484     88.687643     89.140431     89.043402     89.554104     89.385594   

     (0, 1, 4, 5)  (0, 2, 3, 4)  (0, 2, 3, 5)  (0, 2, 4, 5)  (0, 3, 4, 5)  

In [40]:
distances_full = []
for row in data_full.iloc[:,:-1].iterrows():
    tmp = []
    for j in range(0,len(row[1])):
        for k in range(j+1, len(row[1])):
            tmp.append(count_euclid_dist(row[1][j], row[1][k]))
    distances_full.append(tmp)

distances_full = pd.DataFrame(distances_full)
distances_full.columns = [(j,k) for j in range(0, data.shape[1]-1) for k in range(j+1, data.shape[1]-1)]
print(distances_full)

       (0, 1)     (0, 2)     (0, 3)     (0, 4)     (0, 5)    (1, 2)  \
0    5.779173  10.408801  11.444119  15.727503  18.719263  5.375071   
1    5.381407  10.583290  11.737288  15.152251  18.619292  5.472435   
2    5.636350  10.709473  11.874037  15.511510  18.396127  5.301469   
3    5.691740  12.453033  11.218940  14.462211  19.900898  7.112266   
4    5.504531  10.690357  12.940633  16.508203  19.224170  5.637381   
..        ...        ...        ...        ...        ...       ...   
480  6.801267  10.892784  10.169178  10.282740  15.287081  5.899845   
481  7.277024  12.041670  17.578459  21.354883  24.077245  4.876716   
482  6.976323  12.280091  17.305123  21.949537  27.465964  5.571288   
483  5.128902   8.564420  13.519972  18.615035  21.177380  6.059028   
484  6.272024  12.038884  16.553381  19.550443  15.859312  5.908233   

        (1, 3)     (1, 4)     (1, 5)    (2, 3)     (2, 4)     (2, 5)  \
0     8.906705  13.842003  17.022822  6.054265  11.441985  15.473133   
1  

In [41]:
df = pd.concat([planar_angles_full, torsion_angles_full, distances_full], axis=1)
df

(0, 1, 2)   (0, 1, 3)   (0, 1, 4)   (0, 1, 5)   (0, 2, 3)   (0, 2, 4)  \
0    137.839805  100.205275   98.031855   97.956593   83.608979   91.946891   
1    154.359694  114.961624  103.852525  100.259138   86.501496   88.408977   
2    156.532646  114.612641  104.592758   98.082748   86.041682   89.669105   
3    152.937440  105.008780   96.914646   99.781813   63.802542   77.195882   
4    147.261946  116.237231  105.980836  100.468988   98.768014   95.742054   
..          ...         ...         ...         ...         ...         ...   
480  117.927979   92.526799   75.117653   75.428839   68.878788   59.669807   
481  164.111401  142.303180  131.077569  116.499055  133.570495  124.681217   
482  156.142769  136.131746  154.124673  152.996751  129.997702  162.705528   
483   99.568944   99.285071   94.981267   81.411478  143.209288  136.682369   
484  162.516019  149.324156  135.179147  114.488806  139.122213  122.215503   

      (0, 2, 5)   (0, 3, 4)   (0, 3, 5)   (0, 4, 5)  ...    (1, 2)     (1, 3)  \
0     90.471345  122.380521  109.385103  111.651048  ...  5.375071   8.906705   
1     87.755900  114.905831  107.952750  117.566113  ...  5.472435   8.404280   
2     85.974914  118.767874  107.140346  111.780593  ...  5.301469   8.363997   
3     89.622342  102.255569  103.803069  130.407786  ...  7.112266   8.305664   
4     90.746071  112.651474  103.352577  111.696668  ...  5.637381   9.528197   
..          ...         ...         ...         ...  ...       ...        ...   
480   66.471460   74.644514   86.495463  129.900723  ...  5.899845   7.266188   
481  110.653689  128.558078  112.986942  108.720274  ...  4.876716  11.247931   
482  162.193414  137.002753  159.527099  151.781177  ...  5.571288  11.586595   
483  116.917134  144.290213  116.402846  102.185996  ...  6.059028  11.709167   
484   91.037181  115.621980   71.143704   41.483549  ...  5.908233  10.846797   

        (1, 4)     (1, 5)    (2, 3)     (2, 4)     (2, 5)    (3, 4)  \
0    13.842003  17.022822  6.054265  11.441985  15.473133  6.278816   
1    12.934476  16.891977  5.761968  11.141472  15.739021  5.839447   
2    13.100788  16.736832  5.920643  11.283166  15.728039  5.786343   
3    12.627513  18.127100  6.502626  10.614387  15.605434  7.050512   
4    14.121574  17.446197  5.842491  11.555048  15.839047  6.413551   
..         ...        ...       ...        ...        ...       ...   
480   9.654321  15.508374  4.332679   9.664717  15.922193  5.787074   
481  15.856715  19.932867  6.960893  12.068445  17.030640  5.385796   
482  15.460441  21.066934  6.631621   9.918917  15.516226  5.850232   
483  17.454720  21.327124  5.650612  11.432304  15.875450  5.881608   
484  14.595157  12.196727  5.455425  10.269600  10.108288  5.468960   

        (3, 5)    (4, 5)  
0    11.494371  5.890362  
1    11.281940  5.881994  
2    10.980576  5.687192  
3    13.977024  7.201625  
4    11.538676  5.485571  
..         ...       ...  
480  12.052674  6.498573  
481  10.963206  6.209780  
482  10.578650  6.088782  
483  11.361388  6.905841  
484   7.824985  5.491507  

[485 rows x 50 columns]

In [42]:
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

In [43]:
df_norm = preprocessing.normalize(df) 
data_full = data_full.reset_index(drop=True)   #base dataframe with nucleotides coords and class
y = data_full['class']
data_full

N1                              N2  \
0          [71.679, 27.885, 13.362]         [75.126, 29.191, 8.911]   
1          [11.903, 62.561, 20.255]         [12.89, 67.843, 20.548]   
2          [52.497, 35.902, 45.669]         [57.25, 38.924, 45.457]   
3           [-1.686, 76.373, 54.02]        [-1.723, 78.977, 59.081]   
4            [8.277, 2.841, 35.275]         [12.066, 1.936, 39.164]   
..                              ...                             ...   
480     [132.011, 190.437, 175.547]     [125.949, 189.833, 178.571]   
481        [23.333, 56.107, 24.494]        [20.137, 54.122, 18.265]   
482      [223.11, 170.001, 246.614]     [220.803, 164.701, 242.708]   
483       [-56.781, 59.391, 72.597]       [-52.814, 60.944, 69.741]   
484  [69.73546, 47.97945, 22.29318]  [71.96684, 52.44792, 26.08686]   

                                 N3                             N4  \
0           [80.361, 30.047, 8.043]       [82.139, 32.527, 13.272]   
1          [11.485, 73.132, 20.547]        [7.281, 72.722, 16.628]   
2          [62.475, 39.792, 45.684]       [63.627, 35.696, 49.801]   
3          [-0.723, 84.602, 63.317]       [-1.274, 87.084, 57.332]   
4           [15.723, 4.163, 42.831]        [18.227, 9.024, 40.773]   
..                              ...                            ...   
480     [124.837, 184.873, 181.566]    [126.079, 182.583, 178.104]   
481         [19.26, 52.457, 13.766]        [22.285, 49.498, 8.239]   
482     [221.244, 160.263, 239.369]     [225.616, 156.34, 236.291]   
483       [-55.822, 63.467, 65.126]      [-58.677, 65.879, 60.888]   
484  [72.34578, 56.70649, 30.16463]  [71.1807, 58.10714, 35.30685]   

                                 N5                              N6  class  
0          [83.259, 38.334, 15.381]        [81.294, 43.869, 14.935]      1  
1            [5.763, 72.86, 10.991]          [7.417, 72.774, 5.347]      1  
2          [64.509, 34.358, 55.361]        [63.005, 35.335, 60.758]      1  
3           [5.354, 88.888, 55.743]        [12.345, 90.194, 56.876]      1  
4          [22.603, 10.952, 36.499]         [25.817, 10.06, 32.144]      1  
..                              ...                             ...    ...  
480     [126.347, 182.483, 172.324]       [125.139, 180.4, 166.288]      0  
481           [26.254, 48.644, 4.7]         [32.002, 46.334, 4.269]      0  
482       [222.44, 153.18, 232.529]     [223.586, 147.392, 231.026]      0  
483       [-62.656, 67.258, 56.782]        [-68.329, 63.59, 55.349]      0  
484  [70.34999, 55.80605, 40.19811]  [69.05458, 51.01681, 37.84402]      0  

[485 rows x 7 columns]

## Naive Bayes

In [112]:
from sklearn.naive_bayes import GaussianNB

#df_norm = preprocessing.normalize(df)   

X_train, X_test, y_train, y_test = train_test_split(df, y, test_size=0.2, random_state=12)

gnb = GaussianNB()
model_GNB = gnb.fit(X_train, y_train)

y_pred_GNB = model_GNB.predict(X_test)

confusion_GNB = confusion_matrix(y_test, y_pred_GNB)
print(confusion_GNB)
print(("Accuracy is"), accuracy_score(y_test, y_pred_GNB) * 100)

[[47  3]
 [ 0 47]]
Accuracy is 96.90721649484536


In [113]:
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import f1_score
print(("Accuracy is"), accuracy_score(y_test, y_pred_GNB) * 100)
print(("Presisions is"), precision_score(y_test, y_pred_GNB) * 100)
print(("Recall is"), recall_score(y_test, y_pred_GNB) * 100)
print(("F1 is"), f1_score(y_test, y_pred_GNB) * 100)

Accuracy is 96.90721649484536
Presisions is 94.0
Recall is 100.0
F1 is 96.90721649484536


## Logistic regression

In [114]:
from sklearn.linear_model import LogisticRegression

X_train, X_test, y_train, y_test = train_test_split(df, y, test_size=0.2, random_state=12)

clf = LogisticRegression(max_iter=10000)
clf.fit(X_train, y_train)

y_pred_LR = clf.predict(X_test)

confusion_LR = confusion_matrix(y_test, y_pred_LR)
print(confusion_LR)
print(("Accuracy is"), accuracy_score(y_test, y_pred_LR) * 100)

[[44  6]
 [ 0 47]]
Accuracy is 93.81443298969072


In [115]:
print(("Accuracy is"), accuracy_score(y_test, y_pred_LR) * 100)
print(("Presisions is"), precision_score(y_test, y_pred_LR) * 100)
print(("Recall is"), recall_score(y_test, y_pred_LR) * 100)
print(("F1 is"), f1_score(y_test, y_pred_LR) * 100)

Accuracy is 93.81443298969072
Presisions is 88.67924528301887
Recall is 100.0
F1 is 94.0


## Drzewo decyzyjne

In [116]:
from sklearn import tree

X_train, X_test, y_train, y_test = train_test_split(df, y, test_size=0.2, random_state=12)

clf = tree.DecisionTreeClassifier()
clf.fit(X_train, y_train)

#tree.plot_tree(clf)

y_pred_TC = clf.predict(X_test)

confusion_TC = confusion_matrix(y_test, y_pred_TC)
print(confusion_TC)
print(("Accuracy is"), accuracy_score(y_test, y_pred_TC) * 100)

[[45  5]
 [ 8 39]]
Accuracy is 86.5979381443299


In [117]:
print(("Accuracy is"), accuracy_score(y_test, y_pred_TC) * 100)
print(("Presisions is"), precision_score(y_test, y_pred_TC) * 100)
print(("Recall is"), recall_score(y_test, y_pred_TC) * 100)
print(("F1 is"), f1_score(y_test, y_pred_TC) * 100)

Accuracy is 86.5979381443299
Presisions is 88.63636363636364
Recall is 82.97872340425532
F1 is 85.71428571428571


## Random forest

In [118]:
from sklearn.ensemble import RandomForestClassifier

X_train, X_test, y_train, y_test = train_test_split(df, y, test_size=0.2, random_state=12)

rf = RandomForestClassifier(n_estimators=30)
rf.fit(X_train, y_train)

y_pred_RF = rf.predict(X_test)

confusion_RF = confusion_matrix(y_test, y_pred_RF)
print(confusion_RF)
print(("Accuracy is"), accuracy_score(y_test, y_pred_RF) * 100)

[[47  3]
 [ 4 43]]
Accuracy is 92.78350515463917


In [119]:
print(("Accuracy is"), accuracy_score(y_test, y_pred_RF) * 100)
print(("Presisions is"), precision_score(y_test, y_pred_RF) * 100)
print(("Recall is"), recall_score(y_test, y_pred_RF) * 100)
print(("F1 is"), f1_score(y_test, y_pred_RF) * 100)

Accuracy is 92.78350515463917
Presisions is 93.47826086956522
Recall is 91.48936170212765
F1 is 92.4731182795699


## SVM

In [120]:
scaler = StandardScaler()
df_std = pd.DataFrame(scaler.fit_transform(df))
df_std.columns=df.columns
df_std

from sklearn import svm

X_train, X_test, y_train, y_test = train_test_split(df_std, y, test_size=0.2, random_state=12)   #lepszy wynik po standaryzacji

clf = svm.SVC()
clf.fit(X_train, y_train)

y_pred_SVM = clf.predict(X_test)

confusion_SVM = confusion_matrix(y_test, y_pred_SVM)
print(confusion_SVM)
print(("Accuracy is"), accuracy_score(y_test, y_pred_SVM) * 100)

[[46  4]
 [ 0 47]]
Accuracy is 95.87628865979381


In [121]:
print(("Accuracy is"), accuracy_score(y_test, y_pred_SVM) * 100)
print(("Presisions is"), precision_score(y_test, y_pred_SVM) * 100)
print(("Recall is"), recall_score(y_test, y_pred_SVM) * 100)
print(("F1 is"), f1_score(y_test, y_pred_SVM) * 100)

Accuracy is 95.87628865979381
Presisions is 92.15686274509804
Recall is 100.0
F1 is 95.91836734693878


In [24]:
X_train

(0, 1, 2)  (0, 1, 3)  (0, 1, 4)  (0, 1, 5)  (0, 2, 3)  (0, 2, 4)  \
62   -0.274736  -0.088395  -0.381881  -0.321627  -0.355455  -0.363577   
64   -0.203645  -0.235970  -0.438113  -0.435048  -0.674628  -0.552677   
71    0.449597   0.135186  -0.030080  -0.154706  -0.339753  -0.237455   
318   0.015847   1.321291   1.355429   0.382990   1.864522   1.492320   
382  -1.151211  -1.668427  -2.021971  -1.692303  -1.351368  -1.749826   
..         ...        ...        ...        ...        ...        ...   
241  -0.964785  -0.896832  -0.722309  -0.518535  -0.391567  -0.550797   
253   0.725227  -1.297162  -0.922277  -0.637162  -0.845809  -0.781595   
390  -1.332258  -1.664840  -0.960809  -1.201470  -0.872351  -0.359949   
155  -0.157946  -0.124726  -0.235689  -0.273960  -0.512724  -0.409231   
331  -0.499456  -0.123359  -0.094818  -0.062038  -0.358572  -0.144852   

     (0, 2, 5)  (0, 3, 4)  (0, 3, 5)  (0, 4, 5)  ...    (1, 2)    (1, 3)  \
62   -0.218911   0.161860   0.355890   0.507127  ... -0.947166 -0.757496   
64   -0.348160   0.216772   0.547571   0.994006  ... -0.279576 -0.805625   
71   -0.205464   0.416066   0.475313   0.553914  ... -0.274485 -0.662975   
318   0.383053   0.262474  -0.614658  -1.307086  ...  0.211426  0.243435   
382  -1.141047  -1.937406  -1.534242  -0.747142  ...  3.048705  1.441387   
..         ...        ...        ...        ...  ...       ...       ...   
241  -0.602704  -0.832332  -0.786990  -0.128412  ... -0.898895  0.234259   
253  -0.622167  -1.286056  -1.533208  -1.484166  ... -0.093051  1.864973   
390  -0.837148  -0.689005  -1.185778  -1.432719  ...  3.195490  1.591852   
155  -0.298216   0.344676   0.571595   0.903291  ... -0.714182 -0.791055   
331  -0.110092   0.578664   0.546974   0.511807  ... -0.332848 -0.681183   

       (1, 4)    (1, 5)    (2, 3)    (2, 4)    (2, 5)    (3, 4)    (3, 5)  \
62  -0.708086 -0.266729 -0.595142 -0.485693 -0.127814  0.472178  0.242076   
64  -0.870046 -0.078976 -0.553166 -0.535915  0.159971  0.269225  0.339760   
71  -0.589123 -0.017116 -0.490793 -0.413764  0.165439  0.075803  0.076785   
318  0.779149  0.272096 -0.326130 -0.106157 -0.235052  0.416879 -0.096693   
382  0.944999 -0.041665  1.868898  1.609905 -0.579025 -0.056930  1.523541   
..        ...       ...       ...       ...       ...       ...       ...   
241 -0.372736  0.184863  0.272443 -0.026960  1.291628  0.324877  3.067752   
253  1.586354 -0.274411  1.959742  1.852249  0.017279 -0.980798 -0.208762   
390  1.490844  0.267779  1.390605  0.758336  0.172241  1.777238  0.549007   
155 -0.901842 -0.079131 -0.541081 -0.535127  0.341456 -0.100693  0.330219   
331 -0.694778 -0.317854 -0.548404 -0.574726 -0.188594 -0.144930 -0.071693   

       (4, 5)  
62  -0.067394  
64  -0.434258  
71  -0.464462  
318  0.761442  
382  1.764997  
..        ...  
241  3.602497  
253 -0.076573  
390  1.501577  
155 -0.222521  
331 -0.438744  

[388 rows x 50 columns]

## Neural Network

In [122]:
import tensorflow as tf
from tensorflow import keras

X_train, X_test, y_train, y_test = train_test_split(df_std, y, test_size=0.2, random_state=12)

model = keras.Sequential(
    [
        keras.layers.Dense(50, activation="relu", name="input_layer"),  
        keras.layers.Dropout(rate=0.5), 
        keras.layers.Dense(32, activation="relu", name="hidden_layer_1"), 
        keras.layers.Dense(16, activation="relu", name="hidden_layer_2"), 
        # keras.layers.Dense(8, activation="relu", name="hidden_layer_3"), 
        keras.layers.Dense(1,  activation='sigmoid', name="output_layer"),
    ]
)

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

checkpoint = keras.callbacks.ModelCheckpoint('best_model', save_best_only=True, monitor='loss', mode='min', verbose=0)

model.fit(X_train, y_train, epochs=10, callbacks=checkpoint)  

Epoch 1/10
13/13 [==============================] - 2s 102ms/step - loss: 0.8496 - accuracy: 0.5387
Epoch 2/10
13/13 [==============================] - 1s 97ms/step - loss: 0.6403 - accuracy: 0.6804
Epoch 3/10
13/13 [==============================] - 2s 142ms/step - loss: 0.4905 - accuracy: 0.8402
Epoch 4/10
13/13 [==============================] - 1s 98ms/step - loss: 0.4011 - accuracy: 0.8866
Epoch 5/10
13/13 [==============================] - 1s 87ms/step - loss: 0.3275 - accuracy: 0.9046
Epoch 6/10
13/13 [==============================] - 1s 82ms/step - loss: 0.3050 - accuracy: 0.9072
Epoch 7/10
13/13 [==============================] - 1s 67ms/step - loss: 0.2901 - accuracy: 0.9201
Epoch 8/10
13/13 [==============================] - 1s 63ms/step - loss: 0.2523 - accuracy: 0.9175
Epoch 9/10
13/13 [==============================] - 1s 62ms/step - loss: 0.2517 - accuracy: 0.9175
Epoch 10/10
13/13 [==============================] - 0s 3ms/step - loss: 0.2547 - accuracy: 0.9175


In [124]:
y_pred_NN = model.predict(X_test)
y_pred_NN = np.where(y_pred_NN > 0.5, 1, 0)
#print(y_pred_NN)
#print(y_test)

test_loss, test_acc = model.evaluate(X_test, y_test)
print(f'Accuracy: {test_acc} loss: {test_loss}')

confusion_NN = confusion_matrix(y_test, y_pred_NN)
print(confusion_NN)
print(("Accuracy is"), accuracy_score(y_test, y_pred_NN) * 100)

4/4 [==============================] - 0s 1ms/step - loss: 0.1591 - accuracy: 0.9691
Accuracy: 0.969072163105011 loss: 0.1590755581855774
[[47  3]
 [ 0 47]]
Accuracy is 96.90721649484536


In [125]:
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import f1_score
print(("Accuracy is"), accuracy_score(y_test, y_pred_NN) * 100)
print(("Presisions is"), precision_score(y_test, y_pred_NN) * 100)
print(("Recall is"), recall_score(y_test, y_pred_NN) * 100)
print(("F1 is"), f1_score(y_test, y_pred_NN) * 100)

Accuracy is 96.90721649484536
Presisions is 94.0
Recall is 100.0
F1 is 96.90721649484536


## GRAPH

In [143]:
# Reading sequences data from CSV file
import csv
seqs = []

with open("./database_F_seqs.csv", 'r') as csvfile:
    csvreader = csv.reader(csvfile)
    for row in csvreader:
        seqs.append(row[0])

with open("./stems_database_P_seqs.csv", 'r') as csvfile:
    csvreader = csv.reader(csvfile)
    for row in csvreader:
        seqs.append(row[0])

with open("./hairpins_database_P_seqs.csv", 'r') as csvfile:
    csvreader = csv.reader(csvfile)
    for row in csvreader:
        seqs.append(row[0])

with open("./loops_database_P_seqs.csv", 'r') as csvfile:
    csvreader = csv.reader(csvfile)
    for row in csvreader:
        seqs.append(row[0])

with open("./ends_database_P_seqs.csv", 'r') as csvfile:
    csvreader = csv.reader(csvfile)
    for row in csvreader:
        seqs.append(row[0])

with open("./mix_database_P_seqs.csv", 'r') as csvfile:
    csvreader = csv.reader(csvfile)
    for row in csvreader:
        if len(seqs) == data_full.shape[0]:
            break
        seqs.append(row[0])

In [144]:
df_std_nucs = df_std.copy()
df_std_nucs['seq'] = seqs
df_std_nucs

(0, 1, 2)  (0, 1, 3)  (0, 1, 4)  (0, 1, 5)  (0, 2, 3)  (0, 2, 4)  \
0    -0.521581  -0.186180  -0.150172  -0.084934  -0.335716  -0.123486   
1     0.879901   0.481723   0.181928   0.070431  -0.218103  -0.310457   
2     1.064246   0.465927   0.224162  -0.076421  -0.236799  -0.243862   
3     0.759243   0.031237  -0.213914   0.038223  -1.141069  -0.903042   
4     0.277756   0.539460   0.303360   0.084591   0.280668   0.077079   
..         ...        ...        ...        ...        ...        ...   
480  -2.210822  -0.533724  -1.457547  -1.605000  -0.934663  -1.829254   
481   1.707197   1.719259   1.735260   1.166224   1.695778   1.606446   
482   1.031170   1.439927   3.050218   3.628915   1.550504   3.615940   
483  -3.768330  -0.227830  -0.324224  -1.201319   2.087703   2.240678   
484   1.571852   2.037043   1.969276   1.030581   1.921517   1.476138   

     (0, 2, 5)  (0, 3, 4)  (0, 3, 5)  (0, 4, 5)  ...    (1, 3)    (1, 4)  \
0    -0.102363   0.658582   0.513769   0.317635  ... -0.637259 -0.523598   
1    -0.270192   0.241598   0.436513   0.597641  ... -0.766641 -0.949285   
2    -0.380267   0.457047   0.392695   0.323767  ... -0.777014 -0.871274   
3    -0.154836  -0.464112   0.212695   1.205538  ... -0.792036 -1.093269   
4    -0.085384   0.115836   0.188397   0.319795  ... -0.477215 -0.392462   
..         ...        ...        ...        ...  ...       ...       ...   
480  -1.585684  -2.004427  -0.720811   1.181535  ... -1.059717 -2.487881   
481   1.145013   1.003205   0.708038   0.178898  ... -0.034356  0.421427   
482   4.330444   1.474301   3.218238   2.217308  ...  0.052855  0.235550   
483   1.532128   1.880840   0.892279  -0.130420  ...  0.084419  1.170990   
484  -0.067392   0.281549  -1.548827  -3.003942  ... -0.137655 -0.170322   

       (1, 5)    (2, 3)    (2, 4)    (2, 5)    (3, 4)    (3, 5)    (4, 5)  \
0   -0.239991 -0.493581 -0.415900 -0.047403  0.095154  0.042754 -0.103027   
1   -0.321284 -0.552562 -0.536618  0.156641 -0.879806 -0.167477 -0.115479   
2   -0.417674 -0.520544 -0.479699  0.148214 -0.997642 -0.465720 -0.405333   
3    0.446087 -0.403110 -0.748353  0.054126  1.807545  2.499698  1.848058   
4    0.023048 -0.536314 -0.370481  0.233402  0.394130  0.086601 -0.705334   
..        ...       ...       ...       ...       ...       ...       ...   
480 -1.180905 -0.840967 -1.129843  0.297208 -0.996021  0.595276  0.801956   
481  1.567995 -0.310640 -0.164246  1.147836 -1.886455 -0.482910  0.372248   
482  2.272581 -0.377081 -1.027729 -0.014333 -0.855872 -0.863484  0.192211   
483  2.434235 -0.575031 -0.419789  0.261337 -0.786249 -0.088851  1.407948   
484 -3.238403 -0.614417 -0.886857 -4.164411 -1.701915 -3.588632 -0.696501   

        seq  
0    CGAAAG  
1    CGAAGG  
2    CGAAGG  
3    CGAAAG  
4    GGGAGC  
..      ...  
480  AAUCCA  
481  AUUUGA  
482  GGAUAG  
483  ACAGUC  
484  GGUUCG  

[485 rows x 51 columns]

In [145]:
X_train, X_test, y_train, y_test = train_test_split(df_std_nucs, y, test_size=0.2, random_state=12)
df_train = pd.concat([X_train, y_train], axis=1).reset_index(drop=True)
df_test = pd.concat([X_test, y_test], axis=1).reset_index(drop=True)

In [129]:
X_train

(0, 1, 2)  (0, 1, 3)  (0, 1, 4)  (0, 1, 5)  (0, 2, 3)  (0, 2, 4)  \
62   -0.274736  -0.088395  -0.381881  -0.321627  -0.355455  -0.363577   
64   -0.203645  -0.235970  -0.438113  -0.435048  -0.674628  -0.552677   
71    0.449597   0.135186  -0.030080  -0.154706  -0.339753  -0.237455   
318   0.015847   1.321291   1.355429   0.382990   1.864522   1.492320   
382  -1.151211  -1.668427  -2.021971  -1.692303  -1.351368  -1.749826   
..         ...        ...        ...        ...        ...        ...   
241  -0.964785  -0.896832  -0.722309  -0.518535  -0.391567  -0.550797   
253   0.725227  -1.297162  -0.922277  -0.637162  -0.845809  -0.781595   
390  -1.332258  -1.664840  -0.960809  -1.201470  -0.872351  -0.359949   
155  -0.157946  -0.124726  -0.235689  -0.273960  -0.512724  -0.409231   
331  -0.499456  -0.123359  -0.094818  -0.062038  -0.358572  -0.144852   

     (0, 2, 5)  (0, 3, 4)  (0, 3, 5)  (0, 4, 5)  ...    (1, 3)    (1, 4)  \
62   -0.218911   0.161860   0.355890   0.507127  ... -0.757496 -0.708086   
64   -0.348160   0.216772   0.547571   0.994006  ... -0.805625 -0.870046   
71   -0.205464   0.416066   0.475313   0.553914  ... -0.662975 -0.589123   
318   0.383053   0.262474  -0.614658  -1.307086  ...  0.243435  0.779149   
382  -1.141047  -1.937406  -1.534242  -0.747142  ...  1.441387  0.944999   
..         ...        ...        ...        ...  ...       ...       ...   
241  -0.602704  -0.832332  -0.786990  -0.128412  ...  0.234259 -0.372736   
253  -0.622167  -1.286056  -1.533208  -1.484166  ...  1.864973  1.586354   
390  -0.837148  -0.689005  -1.185778  -1.432719  ...  1.591852  1.490844   
155  -0.298216   0.344676   0.571595   0.903291  ... -0.791055 -0.901842   
331  -0.110092   0.578664   0.546974   0.511807  ... -0.681183 -0.694778   

       (1, 5)    (2, 3)    (2, 4)    (2, 5)    (3, 4)    (3, 5)    (4, 5)  \
62  -0.266729 -0.595142 -0.485693 -0.127814  0.472178  0.242076 -0.067394   
64  -0.078976 -0.553166 -0.535915  0.159971  0.269225  0.339760 -0.434258   
71  -0.017116 -0.490793 -0.413764  0.165439  0.075803  0.076785 -0.464462   
318  0.272096 -0.326130 -0.106157 -0.235052  0.416879 -0.096693  0.761442   
382 -0.041665  1.868898  1.609905 -0.579025 -0.056930  1.523541  1.764997   
..        ...       ...       ...       ...       ...       ...       ...   
241  0.184863  0.272443 -0.026960  1.291628  0.324877  3.067752  3.602497   
253 -0.274411  1.959742  1.852249  0.017279 -0.980798 -0.208762 -0.076573   
390  0.267779  1.390605  0.758336  0.172241  1.777238  0.549007  1.501577   
155 -0.079131 -0.541081 -0.535127  0.341456 -0.100693  0.330219 -0.222521   
331 -0.317854 -0.548404 -0.574726 -0.188594 -0.144930 -0.071693 -0.438744   

        seq  
62   CUAACG  
64   GGCAAC  
71   GGAGAC  
318  CCUUUG  
382  AUAUAU  
..      ...  
241  CGAAAG  
253  CCUGGG  
390  GUAUGC  
155  UGUGAA  
331  AGAAAU  

[388 rows x 51 columns]

In [131]:
from torch_geometric.data import Data
from torch_geometric.loader import DataLoader
import torch
from sklearn.decomposition import PCA

def get_graph(row, cols):
        edges_dict = {(0,1): [], (0,2): [], (0,3): [], (0,4): [], (0,5): [], 
                      (1,2): [], (1,3): [], (1,4): [], (1,5): [], 
                      (2,3): [], (2,4): [], (2,5): [], 
                      (3,4): [], (3,5): [], 
                      (4,5): []}

        for i in range(len(cols)):
            weigth = row[i]
            if len(cols[i]) == 4:
                edges_dict[(cols[i][0], cols[i][1])].append(weigth)
                edges_dict[(cols[i][0], cols[i][2])].append(weigth)
                edges_dict[(cols[i][0], cols[i][3])].append(weigth)
                edges_dict[(cols[i][1], cols[i][2])].append(weigth)
                edges_dict[(cols[i][1], cols[i][3])].append(weigth)
                edges_dict[(cols[i][2], cols[i][3])].append(weigth)
            elif len(cols[i]) == 3:
                edges_dict[(cols[i][0], cols[i][1])].append(weigth)
                edges_dict[(cols[i][0], cols[i][2])].append(weigth)
                edges_dict[(cols[i][1], cols[i][2])].append(weigth)
            else:
                edges_dict[(cols[i][0], cols[i][1])].append(weigth)

        edge_index_list = torch.tensor([edge for edge in edges_dict.keys()], dtype=torch.int64).t().contiguous()
        #edge_weights = torch.tensor([w for w in edges_dict.values()], dtype=torch.float32)
        
        edge_weights = []
        edges_w = torch.tensor([w for w in edges_dict.values()], dtype=torch.float32)
        for x in edges_w:
            pca = PCA(n_components=1)
            pca.fit(x.reshape(-1, 1))
            edge_weights.append(pca.singular_values_*400)
        edge_weights = torch.tensor(edge_weights, dtype=torch.float32)

        #make graph undirected
        edge_index_symmetric = torch.cat([edge_index_list, edge_index_list.flip(0)], dim=1)
        edge_weights_symmetric = torch.cat([edge_weights, edge_weights])

        d = {'A': 1, 'U': 2, 'C': 3, 'G': 4}
        y = torch.tensor([row['class']], dtype=torch.int64)
        x = torch.tensor([[d[n]] for n in row['seq']], dtype=torch.float32)

        graph = Data(edge_index=edge_index_symmetric, edge_weight=edge_weights_symmetric, y=y, x=x)

        return graph

cols = df_train.columns[:-2]
train_dataset = df_train.apply(lambda x: get_graph(x, cols), axis=1)
test_dataset = df_test.apply(lambda x: get_graph(x, cols), axis=1)

print(f'Number of training graphs: {len(train_dataset)}')
print(f'Number of test graphs: {len(test_dataset)}')

Number of training graphs: 388
Number of test graphs: 97


In [132]:
data = train_dataset[0]  # Get the first graph object.

print(data)
print('=============================================================')

# Gather some statistics about the first graph.
print(f'Number of nodes: {data.num_nodes}')
print(f'Number of edges: {data.num_edges}')
print(f'Average node degree: {data.num_edges / data.num_nodes:.2f}')
print(f'Has isolated nodes: {data.has_isolated_nodes()}')
print(f'Has self-loops: {data.has_self_loops()}')
print(f'Is undirected: {data.is_undirected()}')

print('=============================================================')
print(data.x)
print(data.y)
print(data.edge_index)
#print(data.edge_attr)
print(data.edge_weight)

Data(x=[6, 1], edge_index=[2, 30], y=[1], edge_weight=[30, 1])
Number of nodes: 6
Number of edges: 30
Average node degree: 5.00
Has isolated nodes: False
Has self-loops: False
Is undirected: True
tensor([[3.],
        [2.],
        [1.],
        [1.],
        [3.],
        [4.]])
tensor([1])
tensor([[0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 3, 3, 4, 1, 2, 3, 4, 5, 2, 3, 4, 5,
         3, 4, 5, 4, 5, 5],
        [1, 2, 3, 4, 5, 2, 3, 4, 5, 3, 4, 5, 4, 5, 5, 0, 0, 0, 0, 0, 1, 1, 1, 1,
         2, 2, 2, 3, 3, 4]])
tensor([[439.0039],
        [518.9549],
        [536.7729],
        [568.6334],
        [428.9575],
        [573.3750],
        [526.2974],
        [543.6843],
        [408.8746],
        [566.8457],
        [530.6399],
        [420.7873],
        [432.2153],
        [406.3175],
        [426.2561],
        [439.0039],
        [518.9549],
        [536.7729],
        [568.6334],
        [428.9575],
        [573.3750],
        [526.2974],
        [543.6843],
        [408.8746],
        

In [133]:
#można regulować rozmiar batcha
train_loader = DataLoader(train_dataset, batch_size=32)
test_loader = DataLoader(test_dataset, batch_size=32)

In [134]:
from torch.nn import Sigmoid
import torch.nn.functional as F
from torch_geometric.nn import GCNConv
from torch_geometric.nn import global_mean_pool


class GCN(torch.nn.Module):
    def __init__(self, hidden_channels):
        super(GCN, self).__init__()
        #torch.manual_seed(12345)
        self.conv1 = GCNConv(1, hidden_channels)
        self.conv2 = GCNConv(hidden_channels, hidden_channels)
        self.conv3 = GCNConv(hidden_channels, 1) 
        self.sigm = Sigmoid()

    def forward(self, x, edge_index, edge_weight, batch):
        x = self.conv1(x, edge_index, edge_weight)
        x = x.relu()
        x = self.conv2(x, edge_index, edge_weight)
        x = x.relu()
        x = self.conv3(x, edge_index, edge_weight)

        # 2. Readout layer
        x = global_mean_pool(x, batch) 

        # 3. Apply a final classifier
        x = F.dropout(x, p=0.4, training=self.training)
        x = self.sigm(x)
        
        return x

In [137]:
model = GCN(hidden_channels=64)
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
criterion = torch.nn.BCELoss()

def train():
    model.train()
    for data in train_loader:  # Iterate in batches over the training dataset.
         out = model(data.x, data.edge_index, data.edge_weight, data.batch)  
        # print(out.view(-1))
        #  print(data.y)
         loss = criterion(out.view(-1), data.y.float())  # Compute the loss.
         #print(loss)
         loss.backward()  # Derive gradients.
         optimizer.step()  # Update parameters based on gradients.
         optimizer.zero_grad()  # Clear gradients.

def test(loader):
     model.eval()

     correct = 0
     for data in loader:  # Iterate in batches over the test dataset.
         out = model(data.x, data.edge_index, data.edge_weight, data.batch)  
        #  print(out.view(-1))
         pred = [1 if x >= 0.5 else 0 for x in out]
        #  print(pred)
         for x in range(len(pred)):
             if pred[x] == data.y[x]:
                 correct += 1
     return correct / len(loader.dataset)  # Derive ratio of correct predictions.

def evaluate(loader):
    model.eval()
    all_preds = []
    all_labels = []
    with torch.no_grad():
        for data in loader:
            out = model(data.x, data.edge_index, data.edge_weight, data.batch)
            preds = torch.round(out).view(-1).int()
            all_preds.extend(preds.tolist())
            all_labels.extend(data.y.tolist())
    return all_labels, all_preds


for epoch in range(1, 100):
    train()
    train_acc = test(train_loader)
    test_acc = test(test_loader)
    print(f'Epoch: {epoch:03d}, Train Acc: {train_acc:.4f}, Test Acc: {test_acc:.4f}')

Epoch: 001, Train Acc: 0.6469, Test Acc: 0.5979
Epoch: 002, Train Acc: 0.5541, Test Acc: 0.5258
Epoch: 003, Train Acc: 0.5206, Test Acc: 0.4845
Epoch: 004, Train Acc: 0.4716, Test Acc: 0.5155
Epoch: 005, Train Acc: 0.5206, Test Acc: 0.4845
Epoch: 006, Train Acc: 0.5206, Test Acc: 0.4845
Epoch: 007, Train Acc: 0.5206, Test Acc: 0.4845
Epoch: 008, Train Acc: 0.4820, Test Acc: 0.5155
Epoch: 009, Train Acc: 0.6263, Test Acc: 0.6082
Epoch: 010, Train Acc: 0.5206, Test Acc: 0.4845
Epoch: 011, Train Acc: 0.6546, Test Acc: 0.5773
Epoch: 012, Train Acc: 0.4742, Test Acc: 0.5155
Epoch: 013, Train Acc: 0.4742, Test Acc: 0.5361
Epoch: 014, Train Acc: 0.6443, Test Acc: 0.5773
Epoch: 015, Train Acc: 0.5000, Test Acc: 0.5567
Epoch: 016, Train Acc: 0.4794, Test Acc: 0.5155
Epoch: 017, Train Acc: 0.4768, Test Acc: 0.5155
Epoch: 018, Train Acc: 0.6521, Test Acc: 0.5773
Epoch: 019, Train Acc: 0.5851, Test Acc: 0.5258
Epoch: 020, Train Acc: 0.4897, Test Acc: 0.5567
Epoch: 021, Train Acc: 0.4974, Test Acc:

In [138]:
train_labels, train_preds = evaluate(train_loader)
test_labels, test_preds = evaluate(test_loader)

conf_matrix = confusion_matrix(test_labels, test_preds)
print("Confusion Matrix:")
print(conf_matrix)

print(("Accuracy is"), accuracy_score(test_labels, test_preds) * 100)
print(("Presisions is"), precision_score(test_labels, test_preds) * 100)
print(("Recall is"), recall_score(test_labels, test_preds) * 100)
print(("F1 is"), f1_score(test_labels, test_preds) * 100)

Confusion Matrix:
[[28 22]
 [19 28]]
Accuracy is 57.73195876288659
Presisions is 56.00000000000001
Recall is 59.57446808510638
F1 is 57.731958762886606


## GAT

In [146]:
from torch_geometric.data import Data
from torch_geometric.loader import DataLoader
import torch

def get_graph(row, cols):
        edges_dict = {(0,1): [], (0,2): [], (0,3): [], (0,4): [], (0,5): [], 
                      (1,2): [], (1,3): [], (1,4): [], (1,5): [], 
                      (2,3): [], (2,4): [], (2,5): [], 
                      (3,4): [], (3,5): [], 
                      (4,5): []}

        for i in range(len(cols)):
            weigth = row[i]
            if len(cols[i]) == 4:
                edges_dict[(cols[i][0], cols[i][1])].append(weigth)
                edges_dict[(cols[i][0], cols[i][2])].append(weigth)
                edges_dict[(cols[i][0], cols[i][3])].append(weigth)
                edges_dict[(cols[i][1], cols[i][2])].append(weigth)
                edges_dict[(cols[i][1], cols[i][3])].append(weigth)
                edges_dict[(cols[i][2], cols[i][3])].append(weigth)
            elif len(cols[i]) == 3:
                edges_dict[(cols[i][0], cols[i][1])].append(weigth)
                edges_dict[(cols[i][0], cols[i][2])].append(weigth)
                edges_dict[(cols[i][1], cols[i][2])].append(weigth)
            else:
                edges_dict[(cols[i][0], cols[i][1])].append(weigth)

        edge_index_list = torch.tensor([edge for edge in edges_dict.keys()], dtype=torch.int64).t().contiguous()
        edge_attr = torch.tensor([w for w in edges_dict.values()], dtype=torch.float32)

        #make graph undirected
        edge_index_symmetric = torch.cat([edge_index_list, edge_index_list.flip(0)], dim=1)
        edge_attr_symmetric = torch.cat([edge_attr, edge_attr])

        d = {'A': 1, 'U': 2, 'C': 3, 'G': 4}
        y = torch.tensor([row['class']], dtype=torch.int64)
        x = torch.tensor([[d[n]] for n in row['seq']], dtype=torch.float32)
        #x = torch.tensor([n for n in row[-7:][:-1]], dtype=torch.float32)

        graph = Data(edge_index=edge_index_symmetric, edge_attr=edge_attr_symmetric, y=y, x=x)

        return graph

cols = df_train.columns[:-2]
train_dataset = df_train.apply(lambda x: get_graph(x, cols), axis=1)
test_dataset = df_test.apply(lambda x: get_graph(x, cols), axis=1)

print(f'Number of training graphs: {len(train_dataset)}')
print(f'Number of test graphs: {len(test_dataset)}')

Number of training graphs: 388
Number of test graphs: 97


In [147]:
train_loader = DataLoader(train_dataset, batch_size=32)
test_loader = DataLoader(test_dataset, batch_size=32)

In [148]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch_geometric.nn import GATConv

# Define your GAT model
class GAT(torch.nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim, num_heads):
        super(GAT, self).__init__()
        self.conv1 = GATConv(input_dim, hidden_dim, heads=num_heads)
        self.conv2 = GATConv(hidden_dim * num_heads, hidden_dim, heads=num_heads)
        self.conv3 = GATConv(hidden_dim * num_heads, hidden_dim, heads=num_heads)
        self.conv4 = GATConv(hidden_dim * num_heads, output_dim, heads=1, concat=False)

    def forward(self, data):
        x, edge_index, edge_weight = data.x, data.edge_index, data.edge_attr
        x = self.conv1(x, edge_index, edge_weight)
        x = torch.relu(x)
        x = self.conv2(x, edge_index, edge_weight)
        x = torch.relu(x)
        x = self.conv3(x, edge_index, edge_weight)
        x = torch.relu(x)
        x = self.conv4(x, edge_index, edge_weight)
        x = global_mean_pool(x, data.batch) 
        return torch.sigmoid(x)

# Initialize your GAT model
input_dim = 1  # Dimension of node features
hidden_dim = 86  # Hidden dimension
output_dim = 1  # Output dimension
num_heads = 3  # Number of attention heads
model = GAT(input_dim, hidden_dim, output_dim, num_heads)

# Define loss function and optimizer
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.0015)

# Function to train the model
def train_model(model, train_loader, optimizer, criterion, epochs=300):
    model.train()
    for epoch in range(epochs):
        running_loss = 0.0
        for data in train_loader:
            optimizer.zero_grad()
            output = model(data).view(-1)
            # print(output)
            # print(data.y)
            loss = criterion(output, data.y.float()) 
            loss.backward()
            optimizer.step()
            running_loss += loss.item()
        print(f"Epoch {epoch + 1}, Loss: {running_loss / len(train_loader)}")

# Function to test the model
def test_model(model, test_loader):
    model.eval()
    correct = 0
    total = 0
    with torch.no_grad():
        for data in test_loader:
            output = model(data).view(-1)
            predicted = torch.round(output)
            total += data.y.size(0)
            correct += (predicted == data.y).sum().item()
    accuracy = correct / total
    print(f"Test Accuracy: {accuracy}")

# Train the model
train_model(model, train_loader, optimizer, criterion)

# Test the model
test_model(model, test_loader)

Epoch 1, Loss: 0.7038281468244699
Epoch 2, Loss: 0.7021718850502601
Epoch 3, Loss: 0.6898929247489343
Epoch 4, Loss: 0.6814065117102402
Epoch 5, Loss: 0.6551949015030494
Epoch 6, Loss: 0.6089540123939514
Epoch 7, Loss: 0.5571575852540823
Epoch 8, Loss: 0.5213356797511761
Epoch 9, Loss: 0.4973417360049028
Epoch 10, Loss: 0.4808979630470276
Epoch 11, Loss: 0.46862208384733933
Epoch 12, Loss: 0.4541125228771797
Epoch 13, Loss: 0.44692224034896266
Epoch 14, Loss: 0.4447416915343358
Epoch 15, Loss: 0.44157277391507077
Epoch 16, Loss: 0.4382043549647698
Epoch 17, Loss: 0.4344735030944531
Epoch 18, Loss: 0.43074662868793195
Epoch 19, Loss: 0.42731695679517895
Epoch 20, Loss: 0.42550618373430693
Epoch 21, Loss: 0.42412607027934146
Epoch 22, Loss: 0.4214102350748502
Epoch 23, Loss: 0.4182020448721372
Epoch 24, Loss: 0.4165629606980544
Epoch 25, Loss: 0.4147042700877556
Epoch 26, Loss: 0.4134185795600598
Epoch 27, Loss: 0.41268999301470244
Epoch 28, Loss: 0.4118930972539462
Epoch 29, Loss: 0.411

In [149]:
def test_model_2(model, test_loader):
    model.eval()
    all_preds = []
    all_labels = []
    with torch.no_grad():
        for data in test_loader:
            output = model(data).view(-1)
            predicted = torch.round(output)
            all_preds.append(predicted.cpu().numpy())
            all_labels.append(data.y.cpu().numpy())
    
    all_preds = np.concatenate(all_preds)
    all_labels = np.concatenate(all_labels)
    
    accuracy = (all_preds == all_labels).sum() / len(all_labels)
    precision = precision_score(all_labels, all_preds)
    recall = recall_score(all_labels, all_preds)
    f1 = f1_score(all_labels, all_preds)
    conf_matrix = confusion_matrix(all_labels, all_preds)
    
    print(f"Test Accuracy: {accuracy:.4f}")
    print(f"Precision: {precision:.4f}")
    print(f"Recall: {recall:.4f}")
    print(f"F1 Score: {f1:.4f}")
    print("Confusion Matrix:")
    print(conf_matrix)

# Użyj tej funkcji do testowania modelu
test_model_2(model, test_loader)

Test Accuracy: 0.8557
Precision: 0.7895
Recall: 0.9574
F1 Score: 0.8654
Confusion Matrix:
[[38 12]
 [ 2 45]]
